from __future__ import annotations

import base64
import json
import os
import shutil
import statistics
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any, Callable
from urllib.parse import urlsplit, urlunsplit

import requests
from PIL import Image, ImageDraw, ImageFont

from ..asset_generator import _call_gemini
from ..utils import ensure_dir, write_json, write_text
from .critics import aggregate_reviews, review_candidate
from .planner import collect_visual_relations, compile_image_prompt


def _parse_ratio(value: str) -> float:
    try:
        left, right = str(value).split(":", 1)
        ratio = float(left) / float(right)
        return ratio if ratio > 0 else 16 / 9
    except Exception:
        return 16 / 9


def _image_size(aspect_ratio: str) -> str:
    ratio = _parse_ratio(aspect_ratio)
    if ratio >= 1.25:
        return "1536x1024"
    if ratio <= 0.80:
        return "1024x1536"
    return "1024x1024"


def native_image2_aspect_ratio(aspect_ratio: str) -> str:
    ratio = _parse_ratio(aspect_ratio)
    if ratio >= 1.25:
        return "3:2"
    if ratio <= 0.80:
        return "2:3"
    return "1:1"


def _font(size: int) -> ImageFont.ImageFont:
    for path in [Path(r"C:\Windows\Fonts\msyh.ttc"), Path(r"C:\Windows\Fonts\arial.ttf")]:
        if path.exists():
            try:
                return ImageFont.truetype(str(path), size=size)
            except Exception:
                pass
    return ImageFont.load_default()


def _draw_engineering_placeholder(plan: dict, blueprint: Path, path: Path) -> None:
    with Image.open(blueprint) as source:
        image = source.convert("RGB").copy()
    draw = ImageDraw.Draw(image)
    width, height = image.size
    title = str(plan.get("paper_summary", {}).get("title") or "Paper-to-image engineering preview")
    draw.rectangle((0, 0, width, max(52, round(height * 0.09))), fill=(242, 247, 250))
    draw.text((round(width * 0.025), round(height * 0.025)), title[:100], fill=(31, 57, 74), font=_font(max(16, round(height * 0.03))))
    draw.rectangle((0, height - max(42, round(height * 0.07)), width, height), fill=(255, 244, 230))
    draw.text((round(width * 0.025), height - max(34, round(height * 0.055))), "ENGINEERING ONLY - not generated by Image2 and not production eligible", fill=(142, 72, 43), font=_font(max(13, round(height * 0.02))))
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def _write_openai_image(data: dict, output_path: Path) -> None:
    items = data.get("data") if isinstance(data.get("data"), list) else []
    if not items:
        raise RuntimeError("Image response did not contain data")
    item = items[0]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if item.get("b64_json"):
        output_path.write_bytes(base64.b64decode(item["b64_json"]))
        return
    if item.get("url"):
        response = requests.get(item["url"], timeout=180)
        response.raise_for_status()
        output_path.write_bytes(response.content)
        return
    raise RuntimeError("Image response did not contain b64_json or url")


def _image2_model_name(explicit: str | None = None) -> str:
    model = explicit or os.getenv("RFS_IMAGE_MODEL") or os.getenv("IMAGE_MODEL") or "image-2"
    return "gpt-image-2" if model == "image-2" else model


def _image2_edit_url() -> str:
    explicit = os.getenv("RFS_IMAGE_EDIT_URL", "").strip()
    if explicit:
        return explicit
    base = os.getenv("API_BASE", "").rstrip("/")
    if not base:
        raise RuntimeError("Reference-conditioned Image2 requires API_BASE")
    return f"{base}/images/edits"


def _candidate_failure_modes(record: dict) -> list[str]:
    review = record.get("review", {}) if isinstance(record.get("review"), dict) else {}
    modes = []
    ocr = review.get("ocr", {}) if isinstance(review.get("ocr"), dict) else {}
    scientific = review.get("scientific", {}) if isinstance(review.get("scientific"), dict) else {}
    topology = review.get("topology", {}) if isinstance(review.get("topology"), dict) else {}
    template = review.get("template", {}) if isinstance(review.get("template"), dict) else {}
    aesthetic = review.get("aesthetic", {}) if isinstance(review.get("aesthetic"), dict) else {}
    if ocr.get("missing_labels") or ocr.get("misspelled_labels") or ocr.get("duplicate_labels") or ocr.get("unexpected_labels"):
        modes.append("label_accuracy")
    if scientific.get("missing_modules"):
        modes.append("missing_modules")
    if scientific.get("missing_relations") or topology.get("missing_relations"):
        modes.append("missing_relations")
    if scientific.get("reversed_relations") or topology.get("reversed_relations"):
        modes.append("reversed_relations")
    if topology.get("bypassed_relations"):
        modes.append("bypassed_relations")
    if scientific.get("invented_items") or topology.get("invented_relations"):
        modes.append("invented_content")
    if scientific.get("role_mismatches") or scientific.get("containment_mismatches"):
        modes.append("semantic_role_mismatch")
    if not template.get("passed", False):
        modes.append("template_alignment")
    if not aesthetic.get("passed", False):
        modes.append("aesthetic_quality")
    if review.get("vlm_warning") or review.get("topology_warning"):
        modes.append("review_provider")
    return list(dict.fromkeys(modes or (["unknown_review_failure"] if not record.get("production_pass") else [])))


def _build_stability_report(records: list[dict], failures: list[dict], requested_candidates: int, repair_source: Path | None) -> dict:
    independent = [
        item for item in records
        if str(item.get("candidate_id") or "").startswith("candidate_") and not item.get("repair_source")
    ]
    independent_failures = [
        item for item in failures if str(item.get("candidate_id") or "").startswith("candidate_")
    ]
    seed_count = 0 if repair_source else max(int(requested_candidates), len(independent) + len(independent_failures))
    score_by_id = {str(item.get("candidate_id")): float(item.get("score") or 0.0) for item in independent}
    scores = [score_by_id.get(f"candidate_{index:02d}", 0.0) for index in range(1, seed_count + 1)]
    pass_count = sum(bool(item.get("production_pass")) for item in independent)
    pass_rate = round(pass_count / seed_count, 4) if seed_count else 0.0
    mean_score = round(statistics.fmean(scores), 4) if scores else 0.0
    worst_score = round(min(scores), 4) if scores else 0.0
    deviation = round(statistics.pstdev(scores), 4) if len(scores) >= 2 else 0.0
    failure_modes: dict[str, int] = {}
    candidates = []
    for item in independent:
        modes = _candidate_failure_modes(item)
        for mode in modes:
            failure_modes[mode] = failure_modes.get(mode, 0) + 1
        candidates.append({
            "candidate_id": item.get("candidate_id"),
            "score": round(float(item.get("score") or 0.0), 4),
            "production_pass": bool(item.get("production_pass")),
            "failure_modes": modes,
        })
    for item in independent_failures:
        failure_modes["generation_provider"] = failure_modes.get("generation_provider", 0) + 1
        candidates.append({
            "candidate_id": item.get("candidate_id"),
            "score": 0.0,
            "production_pass": False,
            "failure_modes": ["generation_provider"],
            "error": str(item.get("error") or "candidate generation failed"),
        })
    stable = bool(seed_count >= 2 and pass_rate >= 0.8 and worst_score >= 0.8)
    status = "stable" if stable else "unstable" if seed_count >= 2 else "insufficient_samples"
    return {
        "summary": "Cross-candidate production stability for independent Image2 generations.",
        "status": status,
        "stable": stable,
        "seed_count": seed_count,
        "completed_seed_count": len(independent),
        "production_pass_count": pass_count,
        "production_pass_rate": pass_rate,
        "mean_score": mean_score,
        "worst_case_score": worst_score,
        "standard_deviation": deviation,
        "minimum_recommended_seed_count": 3,
        "candidate_scores": sorted(candidates, key=lambda item: str(item.get("candidate_id") or "")),
        "failure_mode_counts": dict(sorted(failure_modes.items())),
    }


def _safe_endpoint(value: str) -> str:
    parts = urlsplit(value)
    return urlunsplit((parts.scheme, parts.netloc, parts.path, "", ""))


def _call_image2_edit(source_path: Path, prompt: str, output_path: Path, aspect_ratio: str, model: str | None, retries: int) -> dict:
    api_key = os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("Reference-conditioned Image2 requires API_KEY/GEMINI_API_KEY")
    endpoint = _image2_edit_url()
    resolved_model = _image2_model_name(model)
    request_timeout = max(30, int(os.getenv("RFS_IMAGE2_TIMEOUT", "120")))
    last_error: Exception | None = None
    for attempt in range(max(0, min(5, int(retries))) + 1):
        try:
            with source_path.open("rb") as handle:
                response = requests.post(
                    endpoint,
                    headers={"Authorization": f"Bearer {api_key}"},
                    data={"model": resolved_model, "prompt": prompt, "n": "1", "size": _image_size(aspect_ratio)},
                    files={"image": (source_path.name, handle, "image/png")},
                    timeout=request_timeout,
                )
            if response.status_code == 429 or response.status_code >= 500:
                raise RuntimeError(f"Image2 edit returned HTTP {response.status_code}")
            response.raise_for_status()
            _write_openai_image(response.json(), output_path)
            return {"mode": "edit", "model": resolved_model, "endpoint": _safe_endpoint(endpoint), "source": str(source_path), "api_key_present": True}
        except requests.Timeout as exc:
            last_error = exc
            break
        except Exception as exc:
            last_error = exc
            if attempt >= max(0, min(5, int(retries))):
                break
            time.sleep(min(12.0, 1.5 * (2**attempt)))
    raise RuntimeError(f"Reference-conditioned Image2 edit failed: {last_error}")


def _generate_one(prompt: str, plan: dict, blueprint: Path, path: Path, aspect_ratio: str, asset_mode: str, model: str | None, retries: int) -> dict:
    if asset_mode == "placeholder":
        _draw_engineering_placeholder(plan, blueprint, path)
        return {"mode": "placeholder", "model": "offline-placeholder", "engineering_only": True, "api_key_present": bool(os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY"))}
    if asset_mode == "gemini":
        ok = _call_gemini(prompt, aspect_ratio, path, retries=retries)
        if not ok or not path.exists():
            raise RuntimeError("Gemini image generation returned no image")
        return {"mode": "generate", "model": model or "gemini-image", "endpoint": "GEMINI_GEN_IMG_URL", "engineering_only": True, "api_key_present": True}
    return _call_image2_edit(blueprint, prompt, path, aspect_ratio, model, retries)


def _repair_prompt(review: dict, base_prompt: str, plan: dict) -> str:
    connector_checklist = "\n".join(
        f"{index}. {item['source_label']} -> {item['target_label']} [{item['type']}]"
        for index, item in enumerate(collect_visual_relations(plan.get("figure_specification", {})), start=1)
    )
    return f"""
# Summary

Repair the supplied scientific figure while preserving all correct regions. This is a localized Image2 edit, not a redesign.

Preserve:
{json.dumps(review.get('preserve', []), ensure_ascii=False)}

Repair:
{json.dumps(review.get('repair', []), ensure_ascii=False)}

Remove:
{json.dumps(review.get('remove', []), ensure_ascii=False)}

Repair regions:
{json.dumps(review.get('repair_regions', []), ensure_ascii=False)}

Hard errors:
{json.dumps(review.get('hard_errors', []), ensure_ascii=False)}

Mandatory directed connector checklist after repair:
{connector_checklist}

Preserve every currently correct connector. Add or redirect only the connectors named by the repair findings. The repaired image must contain every checklist edge exactly in the stated direction. Never draw a shortcut that bypasses any declared intermediate module.

Original scientific and visual contract:
{base_prompt}
""".strip()


def generate_and_select(
    plan: dict,
    preferences: dict,
    selected_template: dict,
    blueprint_path: str | Path,
    out_dir: str | Path,
    asset_mode: str = "image2",
    candidates: int = 3,
    image_model: str | None = None,
    image_retries: int = 2,
    review_mode: str = "vlm",
    review_model: str | None = None,
    repair_rounds: int = 1,
    repair_source: str | Path | None = None,
    ocr_engine: str = "auto",
    ocr_lang: str = "en_ch",
    ocr_adapter: Callable | None = None,
    critic_adapter: Callable | None = None,
    topology_adapter: Callable | None = None,
    resume_candidates: bool = False,
    require_visual_enrichment: bool = True,
) -> dict:
    root = ensure_dir(out_dir)
    candidate_dir = ensure_dir(root / "candidates")
    prompt_dir = ensure_dir(root / "prompts")
    blueprint = Path(blueprint_path)
    aspect_ratio = str(preferences.get("aspect_ratio") or "16:9")
    count = max(1, min(4, int(candidates)))
    records: list[dict] = []
    failures: list[dict] = []
    requests_manifest: list[dict] = []
    worker_default = min(2, count)
    try:
        candidate_workers = max(1, min(count, int(os.getenv("RFS_PAPER_IMAGE_WORKERS", str(worker_default)))))
    except ValueError:
        candidate_workers = worker_default
    acceptable_aspect_ratios = [
        str(value)
        for value in (preferences.get("requested_aspect_ratio"), preferences.get("aspect_ratio"))
        if value and str(value) != "auto"
    ]

    repair_source_path = Path(repair_source).resolve() if repair_source else None
    if repair_source_path and not repair_source_path.exists():
        raise FileNotFoundError(f"Repair source image does not exist: {repair_source_path}")

    def generate_candidate(index: int) -> dict[str, Any]:
        candidate_id = f"candidate_{index:02d}"
        path = candidate_dir / f"{candidate_id}.png"
        prompt = compile_image_prompt(plan, preferences, candidate_variant=index, selected_template=selected_template)
        prompt_path = prompt_dir / f"{candidate_id}_prompt.txt"
        write_text(prompt_path, prompt)
        started = time.monotonic()
        try:
            if resume_candidates and path.exists():
                generation = {"mode": "existing_candidate_resume", "source": str(path), "api_key_present": bool(os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY"))}
                generation_seconds = 0.0
            else:
                generation_started = time.monotonic()
                generation = _generate_one(prompt, plan, blueprint, path, aspect_ratio, asset_mode, image_model, image_retries)
                generation_seconds = round(time.monotonic() - generation_started, 3)
            review_started = time.monotonic()
            review = review_candidate(path, blueprint, plan, selected_template, mode=review_mode, model=review_model, ocr_engine=ocr_engine, ocr_lang=ocr_lang, ocr_adapter=ocr_adapter, critic_adapter=critic_adapter, topology_adapter=topology_adapter, acceptable_aspect_ratios=acceptable_aspect_ratios, require_visual_enrichment=asset_mode == "image2" and require_visual_enrichment)
            review_seconds = round(time.monotonic() - review_started, 3)
            return {
                "record": {
                    "candidate_id": candidate_id,
                    "path": str(path),
                    "prompt_path": str(prompt_path),
                    "generation": generation,
                    "review": review,
                    "production_pass": bool(asset_mode == "image2" and review["production_pass"]),
                    "score": review["overall_score"],
                    "timings": {
                        "generation_seconds": generation_seconds,
                        "review_seconds": review_seconds,
                        "total_seconds": round(time.monotonic() - started, 3),
                    },
                },
                "request": {"candidate_id": candidate_id, "generation_seconds": generation_seconds, **generation},
            }
        except Exception as exc:
            return {"failure": {"candidate_id": candidate_id, "error": str(exc), "prompt_path": str(prompt_path), "elapsed_seconds": round(time.monotonic() - started, 3)}}

    if repair_source_path:
        candidate_workers = 1
        candidate_id = "source_candidate"
        path = candidate_dir / f"{candidate_id}{repair_source_path.suffix.lower() or '.png'}"
        if path.resolve() != repair_source_path:
            shutil.copyfile(repair_source_path, path)
        prompt = compile_image_prompt(plan, preferences, candidate_variant=1, selected_template=selected_template)
        prompt_path = prompt_dir / f"{candidate_id}_prompt.txt"
        write_text(prompt_path, prompt)
        review_started = time.monotonic()
        review = review_candidate(path, blueprint, plan, selected_template, mode=review_mode, model=review_model, ocr_engine=ocr_engine, ocr_lang=ocr_lang, ocr_adapter=ocr_adapter, critic_adapter=critic_adapter, topology_adapter=topology_adapter, acceptable_aspect_ratios=acceptable_aspect_ratios, require_visual_enrichment=asset_mode == "image2" and require_visual_enrichment)
        review_seconds = round(time.monotonic() - review_started, 3)
        generation = {"mode": "existing_candidate", "source": str(repair_source_path), "api_key_present": bool(os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY"))}
        records.append({
            "candidate_id": candidate_id,
            "path": str(path),
            "prompt_path": str(prompt_path),
            "generation": generation,
            "review": review,
            "production_pass": bool(asset_mode == "image2" and review["production_pass"]),
            "score": review["overall_score"],
            "timings": {"generation_seconds": 0.0, "review_seconds": review_seconds, "total_seconds": review_seconds},
        })
        requests_manifest.append({"candidate_id": candidate_id, "reused_source": True, **generation})
    else:
        with ThreadPoolExecutor(max_workers=candidate_workers) as executor:
            futures = [executor.submit(generate_candidate, index) for index in range(1, count + 1)]
            for future in as_completed(futures):
                result = future.result()
                if result.get("record"):
                    records.append(result["record"])
                    requests_manifest.append(result["request"])
                elif result.get("failure"):
                    failures.append(result["failure"])
        replacement_budget = 0
        if asset_mode == "image2" and count >= 3:
            try:
                replacement_budget = max(0, min(2, int(os.getenv("RFS_STABILITY_REPLACEMENT_RETRIES", "1"))))
            except ValueError:
                replacement_budget = 1
        for replacement_attempt in range(1, replacement_budget + 1):
            retryable = [
                item for item in failures
                if any(token in str(item.get("error") or "").casefold() for token in ("timed out", "timeout", "http 429", "http 5", "provider"))
            ]
            if not retryable:
                break
            for failure in retryable:
                try:
                    candidate_index = int(str(failure.get("candidate_id") or "").rsplit("_", 1)[-1])
                except ValueError:
                    continue
                result = generate_candidate(candidate_index)
                failures.remove(failure)
                if result.get("record"):
                    result["record"]["provider_replacement_attempt"] = replacement_attempt
                    result["request"]["provider_replacement_attempt"] = replacement_attempt
                    records.append(result["record"])
                    requests_manifest.append(result["request"])
                else:
                    replacement_failure = result.get("failure", failure)
                    replacement_failure["provider_replacement_attempts"] = replacement_attempt
                    failures.append(replacement_failure)
    records.sort(key=lambda item: item["candidate_id"])
    requests_manifest.sort(key=lambda item: item["candidate_id"])
    failures.sort(key=lambda item: item["candidate_id"])

    if not records:
        manifest = {"summary": "Image2 request manifest with no successful candidate.", "api_key_present": bool(os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY")), "model": _image2_model_name(image_model) if asset_mode == "image2" else image_model, "edit_endpoint": _image2_edit_url() if asset_mode == "image2" and os.getenv("API_BASE") else None, "candidate_workers": candidate_workers, "requests": requests_manifest, "failures": failures}
        write_json(root / "image2_request_manifest.json", manifest)
        raise RuntimeError(f"All image candidates failed: {failures}")

    passing = [item for item in records if item["production_pass"]]
    repair_records = []
    for repair_index in range(max(0, min(1, int(repair_rounds)))):
        if passing or asset_mode != "image2":
            break
        source = max(records, key=lambda item: item["score"])
        repaired_id = f"repair_{repair_index + 1:02d}"
        repaired_path = candidate_dir / f"{repaired_id}.png"
        base_prompt = Path(source["prompt_path"]).read_text(encoding="utf-8")
        prompt = _repair_prompt(source["review"], base_prompt, plan)
        prompt_path = prompt_dir / f"{repaired_id}_prompt.txt"
        write_text(prompt_path, prompt)
        repair_started = time.monotonic()
        try:
            generation_started = time.monotonic()
            generation = _call_image2_edit(Path(source["path"]), prompt, repaired_path, aspect_ratio, image_model, image_retries)
            generation_seconds = round(time.monotonic() - generation_started, 3)
            requests_manifest.append({"candidate_id": repaired_id, "repair_source": source["candidate_id"], "generation_seconds": generation_seconds, **generation})
            review_started = time.monotonic()
            review = review_candidate(repaired_path, blueprint, plan, selected_template, mode=review_mode, model=review_model, ocr_engine=ocr_engine, ocr_lang=ocr_lang, ocr_adapter=ocr_adapter, critic_adapter=critic_adapter, topology_adapter=topology_adapter, acceptable_aspect_ratios=acceptable_aspect_ratios, require_visual_enrichment=asset_mode == "image2" and require_visual_enrichment)
            review_seconds = round(time.monotonic() - review_started, 3)
            repaired = {"candidate_id": repaired_id, "path": str(repaired_path), "prompt_path": str(prompt_path), "generation": generation, "review": review, "production_pass": review["production_pass"], "score": review["overall_score"], "repair_source": source["candidate_id"], "timings": {"generation_seconds": generation_seconds, "review_seconds": review_seconds, "total_seconds": round(time.monotonic() - repair_started, 3)}}
            repair_records.append(repaired)
            records.append(repaired)
            if repaired["production_pass"]:
                passing.append(repaired)
        except Exception as exc:
            failures.append({"candidate_id": repaired_id, "error": str(exc), "prompt_path": str(prompt_path)})

    aggregates = aggregate_reviews(records)
    for name, data in aggregates.items():
        write_json(root / f"{name}.json", data)
    request_manifest = {"summary": "Safe Image2 request manifest; secrets are never recorded.", "api_key_present": bool(os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY")), "model": _image2_model_name(image_model) if asset_mode == "image2" else image_model, "edit_endpoint": _safe_endpoint(_image2_edit_url()) if asset_mode == "image2" and (os.getenv("API_BASE") or os.getenv("RFS_IMAGE_EDIT_URL")) else None, "blueprint": str(blueprint), "candidate_workers": candidate_workers, "repair_source": str(repair_source_path) if repair_source_path else None, "requests": requests_manifest, "failures": failures}
    write_json(root / "image2_request_manifest.json", request_manifest)

    selected_path = None
    selected = None
    engineering_preview = None
    if passing:
        selected = max(passing, key=lambda item: item["score"])
        selected_path = root / "selected_image.png"
        shutil.copyfile(selected["path"], selected_path)
    elif asset_mode != "image2":
        selected = max(records, key=lambda item: item["score"])
        engineering_preview = root / "engineering_preview.png"
        shutil.copyfile(selected["path"], engineering_preview)

    stability = _build_stability_report(records, failures, count, repair_source_path)
    write_json(root / "stability_report.json", stability)
    report = {"summary": "Generated and reviewed paper-to-image candidates.", "asset_mode": asset_mode, "review_mode": review_mode, "production_eligible": asset_mode == "image2", "requested_candidates": 0 if repair_source_path else count, "candidate_workers": candidate_workers, "resume_candidates": bool(resume_candidates), "repair_source": str(repair_source_path) if repair_source_path else None, "successful_candidates": len(records), "repair_candidates": len(repair_records), "failures": failures, "candidates": records, "stability": stability, "selected_candidate_id": selected["candidate_id"] if selected_path and selected else None, "selected_image": str(selected_path) if selected_path else None, "engineering_preview": str(engineering_preview) if engineering_preview else None, "selected_passed_all_checks": bool(selected_path), "delivery_blocked": asset_mode == "image2" and not selected_path}
    write_json(root / "candidate_review.json", report)
    if report["delivery_blocked"]:
        raise RuntimeError("No Image2 candidate passed scientific, OCR, template, and aesthetic production gates")
    return report
