from __future__ import annotations

import base64
import json
import os
import shutil
import time
from pathlib import Path
from typing import Any, Callable
from urllib.parse import urlsplit, urlunsplit

import requests
from PIL import Image, ImageDraw, ImageFont

from ..asset_generator import _call_gemini
from ..utils import ensure_dir, write_json, write_text
from .critics import aggregate_reviews, review_candidate
from .planner import compile_image_prompt


def _parse_ratio(value: str) -> float:
    try:
        left, right = str(value).split(":", 1)
        ratio = float(left) / float(right)
        return ratio if ratio > 0 else 16 / 9
    except Exception:
        return 16 / 9


def _image_size(aspect_ratio: str) -> str:
    ratio = _parse_ratio(aspect_ratio)
    if ratio >= 1.25:
        return "1536x1024"
    if ratio <= 0.80:
        return "1024x1536"
    return "1024x1024"


def _font(size: int) -> ImageFont.ImageFont:
    for path in [Path(r"C:\Windows\Fonts\msyh.ttc"), Path(r"C:\Windows\Fonts\arial.ttf")]:
        if path.exists():
            try:
                return ImageFont.truetype(str(path), size=size)
            except Exception:
                pass
    return ImageFont.load_default()


def _draw_engineering_placeholder(plan: dict, blueprint: Path, path: Path) -> None:
    with Image.open(blueprint) as source:
        image = source.convert("RGB").copy()
    draw = ImageDraw.Draw(image)
    width, height = image.size
    title = str(plan.get("paper_summary", {}).get("title") or "Paper-to-image engineering preview")
    draw.rectangle((0, 0, width, max(52, round(height * 0.09))), fill=(242, 247, 250))
    draw.text((round(width * 0.025), round(height * 0.025)), title[:100], fill=(31, 57, 74), font=_font(max(16, round(height * 0.03))))
    draw.rectangle((0, height - max(42, round(height * 0.07)), width, height), fill=(255, 244, 230))
    draw.text((round(width * 0.025), height - max(34, round(height * 0.055))), "ENGINEERING ONLY - not generated by Image2 and not production eligible", fill=(142, 72, 43), font=_font(max(13, round(height * 0.02))))
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path)


def _write_openai_image(data: dict, output_path: Path) -> None:
    items = data.get("data") if isinstance(data.get("data"), list) else []
    if not items:
        raise RuntimeError("Image response did not contain data")
    item = items[0]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if item.get("b64_json"):
        output_path.write_bytes(base64.b64decode(item["b64_json"]))
        return
    if item.get("url"):
        response = requests.get(item["url"], timeout=180)
        response.raise_for_status()
        output_path.write_bytes(response.content)
        return
    raise RuntimeError("Image response did not contain b64_json or url")


def _image2_model_name(explicit: str | None = None) -> str:
    model = explicit or os.getenv("RFS_IMAGE_MODEL") or os.getenv("IMAGE_MODEL") or "image-2"
    return "gpt-image-2" if model == "image-2" else model


def _image2_edit_url() -> str:
    explicit = os.getenv("RFS_IMAGE_EDIT_URL", "").strip()
    if explicit:
        return explicit
    base = os.getenv("API_BASE", "").rstrip("/")
    if not base:
        raise RuntimeError("Reference-conditioned Image2 requires API_BASE")
    return f"{base}/images/edits"


def _safe_endpoint(value: str) -> str:
    parts = urlsplit(value)
    return urlunsplit((parts.scheme, parts.netloc, parts.path, "", ""))


def _call_image2_edit(source_path: Path, prompt: str, output_path: Path, aspect_ratio: str, model: str | None, retries: int) -> dict:
    api_key = os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise RuntimeError("Reference-conditioned Image2 requires API_KEY/GEMINI_API_KEY")
    endpoint = _image2_edit_url()
    resolved_model = _image2_model_name(model)
    last_error: Exception | None = None
    for attempt in range(max(0, min(5, int(retries))) + 1):
        try:
            with source_path.open("rb") as handle:
                response = requests.post(
                    endpoint,
                    headers={"Authorization": f"Bearer {api_key}"},
                    data={"model": resolved_model, "prompt": prompt, "n": "1", "size": _image_size(aspect_ratio)},
                    files={"image": (source_path.name, handle, "image/png")},
                    timeout=360,
                )
            if response.status_code == 429 or response.status_code >= 500:
                raise RuntimeError(f"Image2 edit returned HTTP {response.status_code}")
            response.raise_for_status()
            _write_openai_image(response.json(), output_path)
            return {"mode": "edit", "model": resolved_model, "endpoint": _safe_endpoint(endpoint), "source": str(source_path), "api_key_present": True}
        except Exception as exc:
            last_error = exc
            if attempt >= max(0, min(5, int(retries))):
                break
            time.sleep(min(12.0, 1.5 * (2**attempt)))
    raise RuntimeError(f"Reference-conditioned Image2 edit failed: {last_error}")


def _generate_one(prompt: str, plan: dict, blueprint: Path, path: Path, aspect_ratio: str, asset_mode: str, model: str | None, retries: int) -> dict:
    if asset_mode == "placeholder":
        _draw_engineering_placeholder(plan, blueprint, path)
        return {"mode": "placeholder", "model": "offline-placeholder", "engineering_only": True, "api_key_present": bool(os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY"))}
    if asset_mode == "gemini":
        ok = _call_gemini(prompt, aspect_ratio, path, retries=retries)
        if not ok or not path.exists():
            raise RuntimeError("Gemini image generation returned no image")
        return {"mode": "generate", "model": model or "gemini-image", "endpoint": "GEMINI_GEN_IMG_URL", "engineering_only": True, "api_key_present": True}
    return _call_image2_edit(blueprint, prompt, path, aspect_ratio, model, retries)


def _repair_prompt(review: dict, base_prompt: str) -> str:
    return f"""
# Summary

Repair the supplied scientific figure while preserving all correct regions. This is a localized Image2 edit, not a redesign.

Preserve:
{json.dumps(review.get('preserve', []), ensure_ascii=False)}

Repair:
{json.dumps(review.get('repair', []), ensure_ascii=False)}

Remove:
{json.dumps(review.get('remove', []), ensure_ascii=False)}

Repair regions:
{json.dumps(review.get('repair_regions', []), ensure_ascii=False)}

Hard errors:
{json.dumps(review.get('hard_errors', []), ensure_ascii=False)}

Original scientific and visual contract:
{base_prompt}
""".strip()


def generate_and_select(
    plan: dict,
    preferences: dict,
    selected_template: dict,
    blueprint_path: str | Path,
    out_dir: str | Path,
    asset_mode: str = "image2",
    candidates: int = 3,
    image_model: str | None = None,
    image_retries: int = 2,
    review_mode: str = "vlm",
    review_model: str | None = None,
    repair_rounds: int = 1,
    ocr_engine: str = "auto",
    ocr_lang: str = "en_ch",
    ocr_adapter: Callable | None = None,
    critic_adapter: Callable | None = None,
) -> dict:
    root = ensure_dir(out_dir)
    candidate_dir = ensure_dir(root / "candidates")
    prompt_dir = ensure_dir(root / "prompts")
    blueprint = Path(blueprint_path)
    aspect_ratio = str(preferences.get("aspect_ratio") or "16:9")
    count = max(1, min(4, int(candidates)))
    records: list[dict] = []
    failures: list[dict] = []
    requests_manifest: list[dict] = []
    for index in range(1, count + 1):
        candidate_id = f"candidate_{index:02d}"
        path = candidate_dir / f"{candidate_id}.png"
        prompt = compile_image_prompt(plan, preferences, candidate_variant=index, selected_template=selected_template)
        prompt_path = prompt_dir / f"{candidate_id}_prompt.txt"
        write_text(prompt_path, prompt)
        try:
            generation = _generate_one(prompt, plan, blueprint, path, aspect_ratio, asset_mode, image_model, image_retries)
            requests_manifest.append({"candidate_id": candidate_id, **generation})
            review = review_candidate(path, blueprint, plan, selected_template, mode=review_mode, model=review_model, ocr_engine=ocr_engine, ocr_lang=ocr_lang, ocr_adapter=ocr_adapter, critic_adapter=critic_adapter)
            records.append({"candidate_id": candidate_id, "path": str(path), "prompt_path": str(prompt_path), "generation": generation, "review": review, "production_pass": bool(asset_mode == "image2" and review["production_pass"]), "score": review["overall_score"]})
        except Exception as exc:
            failures.append({"candidate_id": candidate_id, "error": str(exc), "prompt_path": str(prompt_path)})

    if not records:
        manifest = {"summary": "Image2 request manifest with no successful candidate.", "api_key_present": bool(os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY")), "model": _image2_model_name(image_model) if asset_mode == "image2" else image_model, "edit_endpoint": _image2_edit_url() if asset_mode == "image2" and os.getenv("API_BASE") else None, "requests": requests_manifest, "failures": failures}
        write_json(root / "image2_request_manifest.json", manifest)
        raise RuntimeError(f"All image candidates failed: {failures}")

    passing = [item for item in records if item["production_pass"]]
    repair_records = []
    for repair_index in range(max(0, min(1, int(repair_rounds)))):
        if passing or asset_mode != "image2":
            break
        source = max(records, key=lambda item: item["score"])
        repaired_id = f"repair_{repair_index + 1:02d}"
        repaired_path = candidate_dir / f"{repaired_id}.png"
        base_prompt = Path(source["prompt_path"]).read_text(encoding="utf-8")
        prompt = _repair_prompt(source["review"], base_prompt)
        prompt_path = prompt_dir / f"{repaired_id}_prompt.txt"
        write_text(prompt_path, prompt)
        try:
            generation = _call_image2_edit(Path(source["path"]), prompt, repaired_path, aspect_ratio, image_model, image_retries)
            requests_manifest.append({"candidate_id": repaired_id, "repair_source": source["candidate_id"], **generation})
            review = review_candidate(repaired_path, blueprint, plan, selected_template, mode=review_mode, model=review_model, ocr_engine=ocr_engine, ocr_lang=ocr_lang, ocr_adapter=ocr_adapter, critic_adapter=critic_adapter)
            repaired = {"candidate_id": repaired_id, "path": str(repaired_path), "prompt_path": str(prompt_path), "generation": generation, "review": review, "production_pass": review["production_pass"], "score": review["overall_score"], "repair_source": source["candidate_id"]}
            repair_records.append(repaired)
            records.append(repaired)
            if repaired["production_pass"]:
                passing.append(repaired)
        except Exception as exc:
            failures.append({"candidate_id": repaired_id, "error": str(exc), "prompt_path": str(prompt_path)})

    aggregates = aggregate_reviews(records)
    for name, data in aggregates.items():
        write_json(root / f"{name}.json", data)
    request_manifest = {"summary": "Safe Image2 request manifest; secrets are never recorded.", "api_key_present": bool(os.getenv("API_KEY") or os.getenv("GEMINI_API_KEY")), "model": _image2_model_name(image_model) if asset_mode == "image2" else image_model, "edit_endpoint": _safe_endpoint(_image2_edit_url()) if asset_mode == "image2" and (os.getenv("API_BASE") or os.getenv("RFS_IMAGE_EDIT_URL")) else None, "blueprint": str(blueprint), "requests": requests_manifest, "failures": failures}
    write_json(root / "image2_request_manifest.json", request_manifest)

    selected_path = None
    selected = None
    engineering_preview = None
    if passing:
        selected = max(passing, key=lambda item: item["score"])
        selected_path = root / "selected_image.png"
        shutil.copyfile(selected["path"], selected_path)
    elif asset_mode != "image2":
        selected = max(records, key=lambda item: item["score"])
        engineering_preview = root / "engineering_preview.png"
        shutil.copyfile(selected["path"], engineering_preview)

    report = {"summary": "Generated and reviewed paper-to-image candidates.", "asset_mode": asset_mode, "review_mode": review_mode, "production_eligible": asset_mode == "image2", "requested_candidates": count, "successful_candidates": len(records), "repair_candidates": len(repair_records), "failures": failures, "candidates": records, "selected_candidate_id": selected["candidate_id"] if selected_path and selected else None, "selected_image": str(selected_path) if selected_path else None, "engineering_preview": str(engineering_preview) if engineering_preview else None, "selected_passed_all_checks": bool(selected_path), "delivery_blocked": asset_mode == "image2" and not selected_path}
    write_json(root / "candidate_review.json", report)
    if report["delivery_blocked"]:
        raise RuntimeError("No Image2 candidate passed scientific, OCR, template, and aesthetic production gates")
    return report
